### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by white8785** [jbfoushee/CLP-Blackjack#1]
# Readme
* Be explicit in your setup instructions.  Is Python 3.10 required?  Can I run an older or newer version?
* Explicitly call out the requirement of a virtual env to be safe
* Include a `git clone $link` also
* After `pip install`, then what?  How do I run it?

# Execution
* data file location isn't obvious - looks like a slashing issue between linux and windows.

**Comment by jbfoushee** [comment]
Denoted Python 3.10 as required.
Called out venv as requirement
Included git clone link
Explained how to run

Fixed data file location between linux and windows
